
// this file is where the information for the compare tool is stored\
//enter information in the " "

const countries = {
    austria: {
        title: "Austria",
        athlete_representation: "Austria - athlete representation TYPE INFO HERE",
        financials: "Austria - financials", 
        funding_model: "Austria - fundingModel", 
        funding_program: "Austria - fundingProgram", 
        media: "Austria - media", 
        performance_trends: "Austria - performance", 
        relationship_with_noc: "Austria - noc", 
        social_change:"Austria - socialChange", 
        sport_management_system:"Austria - sportManagement", 
        staffing_breakdown: "Austria - staffing", 
        strategic_plan: "Austria - strategicPlan", 
        sustainability: "Austria - sustainability", 
        technology:"Austria - technology", 
        where_they_play: "Austria - whereTheyPlay"
    },
    australia: {
        title: "Australia",
        athlete_representation: "Australia - athlete representation",
        financials: "Australia - financials", 
        funding_model: "Australia - fundingModel", 
        funding_program: "Australia - fundingProgram", 
        media: "Australia - media", 
        performance_trends: "Australia - performance", 
        relationship_with_noc: "Australia - noc", 
        social_change:"Australia - socialChange", 
        sport_management_system:"Australia - sportManagement", 
        staffing_breakdown: "Australia - staffing", 
        strategic_plan: "Australia - strategicPlan", 
        sustainability: "Australia - sustainability", 
        technology:"Australia - technology", 
        where_they_play: "Australia - whereTheyPlay"
    },
    country: {
        title: " ",
        athlete_representation: " ",
        financials: " ", 
        funding_model: " ", 
        funding_program: " ", 
        media: " ", 
        performance_trends: " ", 
        relationship_with_noc: " ", 
        social_change: " ", 
        sport_management_system: " ", 
        staffing_breakdown: " ", 
        strategic_plan: " ", 
        sustainability: " ", 
        technology: " ", 
        where_they_play: " "
    },
    france: {
        title: "France",
        athlete_representation: "France - athlete representation",
        financials: "France - financials", 
        funding_model: "France - fundingModel", 
        funding_program: "France - fundingProgram", 
        media: "France - media", 
        performance_trends: "France - performance", 
        relationship_with_noc: "France - noc", 
        social_change:"France - socialChange", 
        sport_management_system:"France - sportManagement", 
        staffing_breakdown: "France - staffing", 
        strategic_plan: "France - strategicPlan", 
        sustainability: "France - sustainability", 
        technology:"France - technology", 
        where_they_play: "France - whereTheyPlay"
    },
    germany: {
        title: "Germany",
        athlete_representation: "Germany - athlete representation",
        financials: "Germany - financials", 
        funding_model: "Germany - fundingModel", 
        funding_program: "Germany - fundingProgram", 
        media: "Germany - media", 
        performance_trends: "Germany - performance", 
        relationship_with_noc: "Germany - noc", 
        social_change:"Germany - socialChange", 
        sport_management_system:"Germany - sportManagement", 
        staffing_breakdown: "Germany - staffing", 
        strategic_plan: "Germany - strategicPlan", 
        sustainability: "Germany - sustainability", 
        technology:"Germany - technology", 
        where_they_play: "Germany - whereTheyPlay"
    },
    italy: {
        title: "Italy",
        athlete_representation: "Italy - athlete representation",
        financials: "Italy - financials", 
        funding_model: "Italy - fundingModel", 
        funding_program: "Italy - fundingProgram", 
        media: "Italy - media", 
        performance_trends: "Italy - performance", 
        relationship_with_noc: "Italy - noc", 
        social_change:"Italy - socialChange", 
        sport_management_system:"Italy - sportManagement", 
        staffing_breakdown: "Italy - staffing", 
        strategic_plan: "Italy - strategicPlan", 
        sustainability: "Italy - sustainability", 
        technology:"Italy - technology", 
        where_they_play: "Italy - whereTheyPlay"
    },
    japan: {
        title: "Japan",
        athlete_representation: "Japan - athlete representation",
        financials: "Japan - financials", 
        funding_model: "Japan - fundingModel", 
        funding_program: "Japan - fundingProgram", 
        media: "Japan - media", 
        performance_trends: "Japan - performance", 
        relationship_with_noc: "Japan - noc", 
        social_change:"Japan - socialChange", 
        sport_management_system:"Japan - sportManagement", 
        staffing_breakdown: "Japan - staffing", 
        strategic_plan: "Japan - strategicPlan", 
        sustainability: "Japan - sustainability", 
        technology:"Japan - technology", 
        where_they_play: "Japan - whereTheyPlay"
    },
    netherlands: {
        title: "Netherlands",
        athlete_representation: "Netherlands - athlete representation",
        financials: "Netherlands - financials", 
        funding_model: "Netherlands - fundingModel", 
        funding_program: "Netherlands - fundingProgram", 
        media: "Netherlands - media", 
        performance_trends: "Netherlands - performance", 
        relationship_with_noc: "Netherlands - noc", 
        social_change:"Netherlands - socialChange", 
        sport_management_system:"Netherlands - sportManagement", 
        staffing_breakdown: "Netherlands - staffing", 
        strategic_plan: "Netherlands - strategicPlan", 
        sustainability: "Netherlands - sustainability", 
        technology:"Netherlands - technology", 
        where_they_play: "Netherlands - whereTheyPlay"
    },
    norway: {
        title: "Norway",
        athlete_representation: "Norway - athlete representation",
        financials: "Norway - financials", 
        funding_model: "Norway - fundingModel", 
        funding_program: "Norway - fundingProgram", 
        media: "Norway - media", 
        performance_trends: "Norway - performance", 
        relationship_with_noc: "Norway - noc", 
        social_change:"Norway - socialChange", 
        sport_management_system:"Norway - sportManagement", 
        staffing_breakdown: "Norway - staffing", 
        strategic_plan: "Norway - strategicPlan", 
        sustainability: "Norway - sustainability", 
        technology:"Norway - technology", 
        where_they_play: "Norway - whereTheyPlay"
    },
    spain: {
        title: "Spain",
        athlete_representation: "Spain - athlete representation",
        financials: "Spain - financials", 
        funding_model: "Spain - fundingModel", 
        funding_program: "Spain - fundingProgram", 
        media: "Spain - media", 
        performance_trends: "Spain - performance", 
        relationship_with_noc: "Spain - noc", 
        social_change:"Spain - socialChange", 
        sport_management_system:"Spain - sportManagement", 
        staffing_breakdown: "Spain - staffing", 
        strategic_plan: "Spain - strategicPlan", 
        sustainability: "Spain - sustainability", 
        technology:"Spain - technology", 
        where_they_play: "Spain - whereTheyPlay"
    },
    united_kingdom: {
        title: "United Kingdom",
        athlete_representation: "United Kingdom - athlete representation",
        financials: "United Kingdom - financials", 
        funding_model: "United Kingdom - fundingModel", 
        funding_program: "United Kingdom - fundingProgram", 
        media: "United Kingdom - media", 
        performance_trends: "United Kingdom - performance", 
        relationship_with_noc: "United Kingdom - noc", 
        social_change:"United Kingdom - socialChange", 
        sport_management_system:"United Kingdom - sportManagement", 
        staffing_breakdown: "United Kingdom - staffing", 
        strategic_plan: "United Kingdom - strategicPlan", 
        sustainability: "United Kingdom - sustainability", 
        technology:"United Kingdom - technology", 
        where_they_play: "United Kingdom - whereTheyPlay"
    },
    usa: {
        title: "USA",
        athlete_representation: "USA - athlete representation",
        financials: "usa - financials", 
        funding_model: "usa - fundingModel", 
        funding_program: "usa - fundingProgram", 
        media: "usa - media", 
        performance_trends: "usa - performance", 
        relationship_with_noc: "usa - noc", 
        social_change:"usa - socialChange", 
        sport_management_system:"usa - sportManagement", 
        staffing_breakdown: "usa - staffing", 
        strategic_plan: "usa - strategicPlan", 
        sustainability: "usa - sustainability", 
        technology:"usa - technology", 
        where_they_play: "usa - whereTheyPlay"
    }
};

 

